LLNL/Abmarl

admiral/envs/__init__.py
admiral/envs/agent_based_simulation.py
admiral/envs/components/actor.py
admiral/envs/components/agent.py
admiral/envs/components/examples/bird_fighting.py
admiral/envs/components/examples/bird_flight.py
admiral/envs/components/examples/fighting_for_resources.py
admiral/envs/components/examples/fighting_teams.py
admiral/envs/components/examples/observing_agent_example.py
admiral/envs/components/examples/predator_prey_example.py
admiral/envs/components/examples/resource_management.py
admiral/envs/components/examples/simple_particle.py
admiral/envs/components/observer.py
admiral/envs/corridor/corridor.py
admiral/envs/corridor/multi_corridor.py
tests/helpers.py
tests/test_corridor.py
tests/test_flatten_wrapper.py
tests/test_movement_component.py
tests/test_multi_corridor.py
tests/test_position_component.py
tests/test_position_restricted_observers_component.py
tests/test_ravel_discrete_wrapper.py
tests/test_sar_wrapper.py

Admiral 49 distinguish acting observing state agents

---

admiral/envs/components/actor.py
admiral/envs/components/examples/simple_particle.py

Added landmarks as agents in simple particle example

---

admiral/envs/components/actor.py
admiral/envs/components/agent.py
admiral/envs/components/examples/simple_particle.py
admiral/envs/components/state.py
tests/test_collision_component.py

@glatt1 Initial implementation of a collision actor. Please take a look and let me know if I've missed anything when I moved them over. The behavior of the particles seems a little weird to me, so I just want to check that I got the implementation correct.
I'm a bit confused about the purpose of `undo_overlap`. Is it trying to capture collisions that happened sometime between the two time-steps, and then move the agent positions back to that location?

Admiral 42 collisions

---

admiral/envs/components/agent.py
admiral/envs/components/hackathon_prototype_components.py
tests/test_seed.py

Admiral 47 exactly reproducible experiments

---

admiral/envs/components/actor.py
admiral/envs/components/agent.py
tests/test_attacking_component.py

Attack result is stochastic according to Bernoulli distribution. Each agent has an attack accuracy (default 1.0 = deterministic), which is the probability of success.

Agents have attack accuracy that determines result in stochastic attacks

---

admiral/envs/components/actor.py
admiral/envs/components/examples/bird_fighting.py
admiral/envs/components/examples/bird_flight.py
admiral/envs/components/examples/comms_team_battle.py
admiral/envs/components/examples/fighting_for_resources.py
admiral/envs/components/examples/fighting_teams.py
admiral/envs/components/examples/observing_agent_example.py
admiral/envs/components/examples/predator_prey_example.py
admiral/envs/components/examples/resource_management.py
admiral/envs/components/examples/simple_particle.py
tests/test_attacking_component.py
tests/test_collision_component.py
tests/test_component_observer_wrapper.py
tests/test_movement_component.py
tests/test_resources_component.py

Admiral 58 actor handles action

---

admiral/envs/components/actor.py
admiral/envs/components/agent.py
admiral/envs/components/done.py
admiral/envs/components/examples/bird_fighting.py
admiral/envs/components/examples/bird_flight.py
admiral/envs/components/examples/comms_team_battle.py
admiral/envs/components/examples/fighting_for_resources.py
admiral/envs/components/examples/fighting_teams.py
admiral/envs/components/examples/observing_agent_example.py
admiral/envs/components/examples/predator_prey_example.py
admiral/envs/components/examples/resource_management.py
admiral/envs/components/examples/simple_particle.py
admiral/envs/components/observer.py
admiral/envs/components/state.py
admiral/envs/components/wrappers/observer_wrapper.py
tests/test_attacking_component.py
tests/test_collision_component.py
tests/test_component_observer_wrapper.py
tests/test_done_component.py
tests/test_health_component.py
tests/test_movement_component.py
tests/test_position_component.py
tests/test_resources_component.py

Fundamental agent attributes are captured in the main Agent class and all other components can assume that those attributes exist without having to check for them.
Resolves #69

Admiral 69 combine attributes into one

---

admiral/envs/components/actor.py
admiral/envs/components/examples/bird_fighting.py
admiral/envs/components/examples/comms_team_battle.py
admiral/envs/components/examples/fighting_for_resources.py
admiral/envs/components/examples/fighting_teams.py
admiral/envs/components/examples/observing_agent_example.py
admiral/envs/components/examples/predator_prey_example.py
admiral/envs/components/examples/resource_management.py
admiral/envs/components/examples/simple_particle.py
admiral/envs/components/observer.py
tests/test_component_observer_wrapper.py
tests/test_position_component.py
tests/test_resources_component.py

Streamlined observer design
Resolves #76

Admiral 76 smart observer

---

admiral/managers/simulation_manager.py
examples/analysis_prototype.py
examples/predator_prey/movement_map.py
examples/predator_prey/runnable_predator_prey_training.py
tests/test_all_step_multi_corridor.py
tests/test_turn_based_multi_corridor.py

Admiral 98 unwrap to manager and abs

---

admiral/scripts/analyze_script.py
admiral/scripts/visualize_script.py
admiral/stage.py

Seed argument for visualize and analyze that leverages ray's seed arg in the tune configuration.
Resolves #106

Admiral 106 seed in visualize

---

.github/workflows/build-docs.yml
docs/Makefile

Added a CI test for building sphinx doc. Test fails on warnings.
Resolves #113

Admial 113 ci test docs build

---

README.md

Updated Readme.md, including badges.
Resolves #115

Admiral 115 modernize the readme

---

.github/workflows/lint.yml

Adding linter for docs directory

---

admiral/sim/corridor/multi_corridor.py
admiral/sim/predator_prey/predator_prey.py
docs/src/overview.rst
docs/src/tutorials/multi_corridor.rst
docs/src/tutorials/predator_prey.rst
examples/multi_corridor_example.py

Admiral 123 align docs and code

---

admiral/stage.py
docs/src/api.rst
docs/src/overview.rst
docs/src/tutorials/predator_prey.rst
examples/analysis_prototype.py
examples/predator_prey/movement_map.py

Updated stage to give the analysis subscript the simulation manager instead of the external wrapped sim. Updated docs for analysis with more detailed analysis function.
Resolves #124

Admiral 124 anaylze gets sim man

---

README.md
abmarl/algs/monte_carlo.py
abmarl/sim/predator_prey/predator_prey.py
abmarl/stage.py
abmarl/tools/numpy_utils.py
abmarl/tools/utils.py
docs/src/highlights.rst
docs/src/install.rst

Abmarl 135 quick cleanups

---

docs/src/featured_usage.rst
docs/src/index.rst

Abmarl 138 highlights section name change

---

docs/src/tutorials/multi_corridor.rst
docs/src/tutorials/predator_prey.rst

Added links to the files for the tutorials

---

docs/src/install.rst

Resolves #173
Doc changes can be found [here](https://abmarl.readthedocs.io/en/abmarl-173-dependency-in-installation/install.html)
@abhiramm7, is this what you had in mind?

Dependency list in installation instructions.

---

README.md
docs/src/conf.py
docs/src/install.rst
setup.py

Version 0.1.3 corrects dependencies in setup

---

docs/src/tutorials/gym.rst
docs/src/tutorials/tutorials.rst
examples/gym_example.py

Abmarl 168 gym example

---

abmarl/train.py
docs/src/overview.rst

train uses local dir as base directory for output

---

abmarl/sim/gridworld/examples/multi_grid_example.py
abmarl/sim/gridworld/observer.py

Multi-grid observer sees a grid for every encoding.
Resolves #193

Abmarl 193 multi dim grid obs

---

publications/paper.bib
publications/paper.md

@danielskatz here are the same changes to the release branch.

Minor changes to paper

---

abmarl/sim/gridworld/agent.py
abmarl/sim/gridworld/base.py
abmarl/sim/gridworld/examples/gridworld_example.py
abmarl/sim/gridworld/examples/multi_grid_example.py
abmarl/sim/gridworld/examples/overlappable_example.py
abmarl/sim/gridworld/grid.py
abmarl/sim/gridworld/state.py

Creating overlapping agent matrix that works similar to attack matrix. Users can control which agent types can overlap with others.
Resolves #191

Abmarl 191 overlapping agent matrix

---

abmarl/sim/gridworld/actor.py
abmarl/sim/gridworld/observer.py
abmarl/sim/gridworld/utils.py

Consolidated some duplicate code for masking and making local grids into a utilities file.
Resolves #158

Abmarl 158 gridworld clean up

---

abmarl/sim/gridworld/actor.py
abmarl/sim/gridworld/done.py

Abmarl 205 more features

---

abmarl/sim/gridworld/agent.py
abmarl/sim/gridworld/examples/gridworld_example.py
abmarl/sim/gridworld/examples/multi_grid_example.py
abmarl/sim/gridworld/examples/overlappable_example.py
abmarl/sim/gridworld/observer.py
abmarl/sim/gridworld/utils.py
tests/sim/gridworld/test_agent.py
tests/sim/gridworld/test_observer.py

Converted view-blocking into just blocking

---

abmarl/sim/gridworld/observer.py
tests/sim/gridworld/test_observer.py

Abmarl 225 single grid observer cast fix

---

abmarl/scripts/visualize_script.py
abmarl/stage.py

Steps per episode added to visualize command

---

abmarl/debug.py
abmarl/scripts/debug_script.py
abmarl/scripts/scripts.py

Added debug functionality to test run the simulation.
Resolves #159

Abmarl 159 debugging

---

abmarl/scripts/scripts.py

Print out help message if no args when command line 'abmar'

---

abmarl/external/gym_env_wrapper.py
docs/requirements.txt
docs/src/api.rst

Abmarl 247 fix docs build fails

---

abmarl/sim/gridworld/wrapper.py
docs/src/api.rst
docs/src/gridworld.rst
docs/src/overview.rst

Helps #229 get closer to closing

Abmarl 0 docs updates for next release

---

abmarl/sim/agent_based_simulation.py
abmarl/sim/gridworld/grid.py
tests/sim/gridworld/test_grid.py

Abmarl 261 grid overlapping non active agents

---

requirements.txt
setup.py

Set rllib version to 1.6.0

---

requirements.txt
setup.py

Upgrade ray dependency to 1.9.0.
Don't close branch, still working on it. Just merging this into main for now.

Abmarl epic 263 upgrade ray version

---

docs/src/overview.rst
docs/src/tutorials/multi_corridor.rst
examples/config_prototype.py

Added some notes to the docs about environment checking.
Resolves #77

Abmarl 277 env checking disable in docs

---

.github/workflows/build-docs.yml
abmarl/managers/__init__.py
abmarl/managers/dynamic_order_manager.py
abmarl/managers/turn_based_manager.py
abmarl/sim/__init__.py
abmarl/sim/agent_based_simulation.py
docs/requirements.txt
docs/src/api.rst
docs/src/overview.rst
tests/sim/test_agent_based_simulation.py
tests/test_dynamic_order_manager.py

Added the dynamic order manager and dynamic order simulation.
Resolves #285 
Resolves #186
Thanks @Leonardo767

Abmarl 285 dynamic order manager

---

abmarl/sim/wrappers/super_agent_wrapper.py
examples/team_battle_super_agent.py
tests/sim/wrappers/test_super_agent_wrapper.py

Added some logic for dealing with observations and rewards from done agents when using the super agent wrapper.
Resolves #290

Abmarl 290 super agent wrapper dead agents track done agents

---

abmarl/sim/wrappers/flatten_wrapper.py

Removed redundant agent copy in flatten wrapper

---

abmarl/examples/sim/multi_agent_sim.py
abmarl/sim/wrappers/flatten_wrapper.py
abmarl/sim/wrappers/ravel_discrete_wrapper.py
tests/test_flatten_wrapper.py
tests/test_ravel_discrete_wrapper.py

Ravel and Flatten Wrappers also ravel and flatten the null observations and actions.
Resolves #304

Abmarl 304 wrappers with null observations

---

abmarl/sim/agent_based_simulation.py
abmarl/sim/gridworld/agent.py

Health agent sets active instead of overwriting it.
Resolves #222

Active can be set directy

---

abmarl/sim/gridworld/actor.py
tests/sim/gridworld/test_actor.py

Added encoding based attack actor

Abmarl epic 68 attack variations encoding based attack

---

abmarl/sim/gridworld/actor.py
abmarl/sim/gridworld/agent.py
tests/sim/gridworld/test_actor.py

Restricted Selective Attack Actor

Abmarl epic 68 attack variations restricted selective attack

---

abmarl/sim/gridworld/wrapper.py
tests/sim/gridworld/test_wrapper.py

Component wrappers implement `unwrap_point` and use that to deal with the null_action. 
Resolves #329

Abmarl 329 component wrapper null points

---

abmarl/examples/sim/multi_agent_sim.py
abmarl/external/gym_env_wrapper.py
tests/test_gym_wrapper.py

GymWrapper now works when there are multiple agents and only one of them is a learning agent.
Resolves #330

GymWrapper single agnt interpretation

---

requirements.txt
setup.py

importlib-metadata version must be less than 5.0 for compliance with gym

---

abmarl/examples/sim/team_battle_example.py

Closes #334 
Updated the code for the team battle game.

fix:update process attacks to work for list of agents instead of single agent

---

examples/multi_corridor_example.py
requirements.txt
setup.py

Upgraded ray dependency to 2.0.0
Resolves #339

Abmarl 0 random policy

---

abmarl/examples/sim/reach_the_target.py
abmarl/examples/sim/team_battle_example.py
abmarl/sim/gridworld/actor.py
tests/sim/gridworld/test_actor.py
tests/sim/gridworld/test_wrapper.py

Attack actors output actor status and list of attacked agents. The status if False if agent chose not to attack or if agent is not an attacking agent. Otherwise it is true. The list of attacked agents is nonempty only if an attack was successful.
Resolves #325

Abmarl 325 ambiguous attack actor outcome

---

abmarl/trainers/debug.py
examples/debug_example.py
tests/trainers/test_debug_trainer.py

Abmarl 315 debug trainer output directory

---

abmarl/sim/gridworld/grid.py
tests/sim/gridworld/test_grid.py

Grid does not check for inactive agent in query

---

abmarl/sim/gridworld/base.py
examples/maze.txt

Reserved _ and . as empty space

---

docs/src/overview.rst
docs/src/tutorials/multi_corridor.rst
examples/multi_corridor_example.py

Disable env precheck not require for turn based games

---

abmarl/sim/gridworld/observer.py
tests/sim/gridworld/test_observer.py

Added absolute position observer, which can work with a grid observer because they have different channels.
Resolves #349

Abmarl 349 absolute position obsersvation

---

abmarl/debug.py
abmarl/trainers/debug.py
examples/debug_example.py

Debug script utilizes debug trainer logic for output directory and name.
Resolves #351

Abmarl 351 debug duplicate directory dating

---

abmarl/examples/sim/multi_corridor.py
abmarl/managers/all_step_manager.py
abmarl/managers/simulation_manager.py
tests/test_all_step_multi_corridor.py

Abmarl 365 random agent order all step manager

---

.github/workflows/build-and-test.yml
.github/workflows/build-docs.yml
.github/workflows/lint.yml
abmarl/sim/gridworld/observer.py

Abmarl 368 numpy int error

---

.github/workflows/build-and-test.yml
.github/workflows/build-docs.yml
.github/workflows/lint.yml
.readthedocs.yaml
README.md
setup.py

Added support for python 3.9 and 3.10

---

abmarl/sim/wrappers/ravel_discrete_wrapper.py
requirements.txt
setup.py
tests/sim/test_agent_based_simulation.py

Using get inf from newer versions of gym

---

abmarl/sim/gridworld/actor.py
tests/sim/gridworld/test_actor.py

Abmarl 374 cross move actor

---

.github/workflows/lint.yml
abmarl/examples/__init__.py
abmarl/examples/sim/__init__.py
abmarl/examples/sim/maze_navigation.py
abmarl/examples/sim/multi_maze_navigation.py
abmarl/sim/gridworld/state.py
abmarl/sim/gridworld/utils.py
examples/multi_maze_navigation_rllib.py
tests/sim/gridworld/test_state.py
tests/sim/gridworld/test_utils.py

Position State partitioned into sub-functions for better overwriting support.
Added maze-generation utility
Added maze-placement state manager
Option to ignore overlapping on reset
Resolves #383 #386 #388 #389

Abmarl 386 position state enhacement

---

abmarl/sim/gridworld/done.py
tests/sim/gridworld/test_done.py

Target done feature

---

abmarl/sim/gridworld/state.py
tests/sim/gridworld/test_state.py

Abmarl 403 place barriers around target

---

abmarl/trainers/base.py
abmarl/trainers/debug.py
examples/debug_example.py

Debug outputs `episode_by_agent` and `episode_by_event`.
Resolves #298

Abmarl 298 debug play by play

---

abmarl/examples/sim/multi_maze_navigation.py
abmarl/managers/turn_based_manager.py

Abmarl 364 turn based manager final output

---

abmarl/examples/sim/comms_blocking.py
abmarl/examples/sim/multi_agent_sim.py
abmarl/examples/sim/multi_corridor.py
abmarl/sim/gridworld/actor.py
abmarl/sim/gridworld/observer.py
abmarl/sim/wrappers/flatten_wrapper.py
abmarl/sim/wrappers/ravel_discrete_wrapper.py
abmarl/tools/__init__.py
abmarl/tools/gym_utils.py
docs/src/overview.rst
docs/src/tutorials/gridworld/communication.rst
docs/src/tutorials/multi_corridor.rst
tests/sim/gridworld/test_actor.py
tests/sim/gridworld/test_observer.py
tests/sim/gridworld/test_wrapper.py
tests/test_flatten_wrapper.py
tests/test_multi_corridor.py
tests/test_ravel_discrete_wrapper.py
tests/tools/test_gym_utils.py
tests/trainers/test_single_policy_trainer.py

Abmarl overwrites gym Box to support numerical values considered as elements of Box.
Resolves #62

Abmarl 62 box numeric values

---

abmarl/examples/sim/maze_navigation.py
abmarl/examples/sim/team_battle_example.py
abmarl/sim/agent_based_simulation.py
abmarl/sim/gridworld/base.py
abmarl/sim/gridworld/registry.py
abmarl/sim/gridworld/smart.py
examples/rllib_maze_navigation.py
examples/rllib_team_battle.py
tests/sim/gridworld/test_registry.py
tests/sim/gridworld/test_smart.py
tests/test_flatten_wrapper.py

Abmarl 72 built in component registry

---

abmarl/sim/gridworld/actor.py
abmarl/sim/gridworld/agent.py
abmarl/sim/gridworld/observer.py
abmarl/sim/gridworld/state.py
tests/sim/gridworld/test_actor.py
tests/sim/gridworld/test_agent.py
tests/sim/gridworld/test_observer.py
tests/sim/gridworld/test_state.py

Abmarl 413 agents with ammo

---

abmarl/examples/sim/comms_blocking.py
abmarl/examples/sim/maze_navigation.py
abmarl/examples/sim/multi_agent_grid_sim.py
abmarl/examples/sim/multi_agent_sim.py
abmarl/examples/sim/multi_maze_navigation.py
abmarl/examples/sim/reach_the_target.py
abmarl/sim/agent_based_simulation.py
abmarl/sim/gridworld/base.py
abmarl/sim/gridworld/smart.py
examples/rllib_super_agent_team_battle.py

Abmarl 429 render on grid

---

abmarl/debug.py

Debug module uses the steps per episode

---

.readthedocs.yaml

Read the docs updated config

---

abmarl/sim/gridworld/actor.py
abmarl/sim/gridworld/agent.py
docs/src/gridworld.rst
tests/sim/gridworld/test_actor.py
tests/sim/gridworld/test_agent.py

Abmarl 427 simultaneous attacks

---

abmarl/examples/sim/comms_blocking.py
abmarl/examples/sim/multi_maze_navigation.py
abmarl/examples/sim/reach_the_target.py
abmarl/sim/gridworld/observer.py
abmarl/sim/gridworld/registry.py
examples/rllib_maze_navigation.py
examples/rllib_super_agent_team_battle.py
examples/rllib_team_battle.py
tests/sim/gridworld/test_observer.py
tests/sim/gridworld/test_registry.py
tests/sim/gridworld/test_smart.py

Abmarl 373 rename observers

---

abmarl/sim/gridworld/done.py
tests/sim/gridworld/test_done.py

Abmarl 411 built in suppport target destroyed done

---

abmarl/sim/gridworld/state.py
tests/sim/gridworld/test_state.py

Abmarl 396 maze placement target by

---

abmarl/debug.py
abmarl/scripts/analyze_script.py
abmarl/scripts/debug_script.py
abmarl/scripts/train_script.py
abmarl/scripts/visualize_script.py
abmarl/stage.py
abmarl/tools/utils.py
abmarl/train.py
abmarl/trainers/debug.py
examples/analysis_prototype.py
examples/full_workflow.py
tests/test_workflow.py

Each cli command is available to be imported and run in a script
Resolves #236

Abmarl epic 236 redo cli scripting

---

.readthedocs.yaml

Fix read the docs config pointer.

Read the docs config points to new req file

---

abmarl/sim/gridworld/state.py
tests/sim/gridworld/test_state.py

Abmarl 452 randomize placement state

---

abmarl/sim/wrappers/flatten_wrapper.py
abmarl/sim/wrappers/ravel_discrete_wrapper.py
tests/test_flatten_wrapper.py
tests/test_ravel_discrete_wrapper.py

Ensure support for flattening gym box

---

.github/workflows/build-and-test.yml
abmarl/stage.py

Reverted bad change to episode save in stage

---

abmarl/sim/gridworld/actor.py

Abmarl 426 attackors check for health

---

abmarl/sim/gridworld/done.py
tests/sim/gridworld/test_done.py

Abmarl 394 target done by encoding

---

abmarl/sim/gridworld/smart.py

Smart sim done is True on any done component

---

tests/sim/gridworld/test_registry.py

Added missing components to registry test

---

abmarl/examples/sim/pacman.py
abmarl/examples/sim/predator_prey_resources.py
abmarl/examples/sim/reach_the_target.py
abmarl/examples/sim/team_battle_example.py
abmarl/sim/gridworld/actor.py
abmarl/sim/gridworld/agent.py
abmarl/sim/gridworld/state.py
docs/src/api.rst
docs/src/gridworld.rst
docs/src/tutorials/gridworld/team_battle.rst
tests/sim/gridworld/test_actor.py
tests/sim/gridworld/test_agent.py
tests/sim/gridworld/test_done.py
tests/sim/gridworld/test_state.py
tests/sim/gridworld/test_wrapper.py

Abmarl 489 gw agent health

---

.github/workflows/lint.yml
abmarl/external/__init__.py
abmarl/external/gym_env_wrapper.py
abmarl/external/rllib_multiagentenv_wrapper.py
tests/external/test_gym_wrapper.py
tests/external/test_rllib_wrapper.py

Abmarl 9 incoming outgoing wrappers
